GRID_NUM = 19
WINDOW_SIZE = (1080, 720)
BOARD_LEN = min(WINDOW_SIZE) * 0.8
OFFSET = ((WINDOW_SIZE[0]-BOARD_LEN)/2, (WINDOW_SIZE[1]-BOARD_LEN)/2)
GRID_LEN = BOARD_LEN / (GRID_NUM-1)
STONE_RADIUS = GRID_LEN * 0.5
X_CORDS = [chr(i) for i in range(ord('A'), ord('A') + GRID_NUM)]  # A-S for 19x19